version: '3.5'
services:
  php-intern_test:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: mvc_php_demo
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - my_network
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: mvc_php
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d/
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
